### ISSUE TITLE
Question About Instagram Android App

### ISSUE THREAD

**Issue by amir-alikhani** [glizzykingdreko/Instagram-Password-Encryption#1]
Thank you for nice repository. it is helpful.
But i need some information about instagram app password encryption. i guess it is a bit different.
i have a sample password string that i bring out from from private api:

#PWD_INSTAGRAM:1:1718273080:ASlTLNCj27WkBI22fLQAAXecurXmxPk33qpx/3dCv6ZiUrBc/9DzGYCKYMV84Py75F57ueCFNDJ8yTf8pTo3R3L2VuIbrQkLhS9IYXUG12gYCjApQredFPP0wKaq2ZOrEWeaMlivoC/Wp3zaR/C2eNRMQFXxgF2L57dJ4XOSfDPChpdVIAQ2a84Gsu1thqUx76tmUXzME2KwyaoXtPyqTG3Rs9B7XhiUgclkUS7FzBYh gix06yj/RqyixhKjNhWPsLTFF3dkHyc/2klAuDvYZMRRcRJiSq10eAv7RUH5Ugoz/Orb4m396yTcFZHMyb iIjq82e2E78qp1WjdRXHpIZJMgHACmSQujWD6rGjwh0Ro8DVknTRRvdR0luVgrUpRdd4jZUW99w2zep

can you give me some help how to create the cipher string??

**Comment by glizzykingdreko** [comment]
Contact me on discord or telegram please `glizzykingdreko`
